In [1]:
from google.colab import files
data_to_load = files.upload()

Saving makeSenseOfCensus.csv to makeSenseOfCensus.csv


In [2]:
import numpy as np

____________________
**Load and read the Data**
____________________

In [3]:
data_file="/content/makeSenseOfCensus.csv"

In [4]:
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)
print("\nData:\n\n ", data)


Data:

  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [5]:
#Printed the type of data
print("\nType of data: \n\n\n", type(data))


Type of data: 


 <class 'numpy.ndarray'>


___________________________________________
**Append the Data**
___________________________________________

In [6]:
#Created new record
new_record = [[50,9,4,1,0,0,40,0]]

In [7]:
#Joined a sequence of arrays along an existing axis
data2=np.concatenate((data,new_record))

In [8]:
data2

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

___________________________________________
**Сheck the age of the population**
___________________________________________

In [9]:
#Created a new array called 'age' by taking only age column
age = data2[:,0]
age

array([39., 50., 38., ..., 40., 39., 50.])

In [10]:
#Found the max age
max_age = max(age)
max_age

90.0

In [11]:
#Found the min age
min_age = min(age)
min_age

17.0

In [12]:
#Found the mean age
age_mean = age.mean()
age_mean

38.06293706293706

In [13]:
##Found the standard deviation of the age
age_std = age.std()
age_std

13.341478176165857

___________________________________________
**Сheck the country's race distribution to identify the minorities**
___________________________________________

In [14]:
#Created five different arrays by subsetting 'census' array by Race column
race_0 = data2[data2[:,2]==0]
race_1 = data2[data2[:,2]==1]
race_2 = data2[data2[:,2]==2]
race_3 = data2[data2[:,2]==3]
race_4 = data2[data2[:,2]==4]


In [15]:
#Stored the length of the above created arrays
len_0=len(race_0)
len_1=len(race_1)
len_2=len(race_2)
len_3=len(race_3)
len_4=len(race_4)

print(len_0, len_1, len_2, len_3, len_4)

10 27 110 6 848


In [16]:
#Found which is the race with the minimum no. of citizens
minority_race = min(len_0, len_1, len_2, len_3, len_4)
print(minority_race)

6


In [17]:
#Stored the number associated with the minority race
if minority_race == len_0:
  minority_race = 0
elif minority_race == len_1:
  minority_race = 1
elif minority_race == len_2:
  minority_race = 2
elif minority_race == len_3:
  minority_race = 3
elif minority_race == len_4:
  minority_race = 4
print('Minority race: ',minority_race)

Minority race:  3


___________________________________________
**According to the law, citizens over 60 years of age must not work more than 25 hours a week. Let's check if the policy is in effect**
___________________________________________

In [18]:
#Created a new subset array called 'senior_citizens'
senior_citizens = data2[data2[:,0]>60]
senior_citizens

array([[7.9000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.7000e+01, 6.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+00, 0.0000e+00],
       [7.6000e+01, 1.4000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 1.0000e+00],
       [6.1000e+01, 9.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [7.0000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [6.4000e+01, 7.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        2.1790e+03, 4.0000e+01, 0.0000e+00],
       [7.1000e+01, 1.0000e+01, 2.0000e+00, 1.0000e+00, 0.0000e+00,
        1.8160e+03, 2.0000e+00, 0.0000e+00],
       [6.8000e+01, 2.0000e+00, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.6000e+01, 1.1000e+01, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+

In [19]:
#Added all the working hours
working_hours_sum = sum(senior_citizens[:,6])
working_hours_sum

1917.0

In [20]:
#Found the length of 'senior_citizens'
senior_citizens_len = len(senior_citizens)
senior_citizens_len

61

In [21]:
#Found the average working hours of the senior citizens
avg_working_hours = working_hours_sum / senior_citizens_len
avg_working_hours

31.42622950819672

___________________________________________
**Сheck that higher educated people have better pay in general.**
___________________________________________

In [22]:
#Create two new subsets according to education
high = data2[data2[:,1]>10]
low = data2[data2[:,1]<=10]
print(high)
print(low)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [28. 13.  2. ...  0. 40.  0.]
 ...
 [45. 14.  4. ...  0. 45.  0.]
 [48. 13.  4. ...  0. 58.  1.]
 [39. 13.  4. ...  0. 50.  1.]]
[[38.  9.  4. ...  0. 40.  0.]
 [53.  7.  2. ...  0. 40.  0.]
 [49.  5.  2. ...  0. 16.  0.]
 ...
 [56.  9.  4. ...  0. 55.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [50.  9.  4. ...  0. 40.  0.]]


In [23]:
#Found the mean of income column
avg_pay_high = high[:,7].mean()
avg_pay_low = low[:,7].mean()
print(avg_pay_high)
print(avg_pay_low)

0.42813455657492355
0.13649851632047477
